### ISSUE TITLE
Code- und Dateistruktur

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-hello-lenny#13]
- Es soll OOP Verwendet werden. Alle Funktionsnamen sind in eine Oberklasse  im Namenspace RRZE\Hello_Lenny einzutragen.
- Die PHP-Dateien/Classen sollen sinnvoll aufgeteilt werden, aber mindestens in der Form:
  - Haupt-Skript:  rrze-hello-lenny.php
- Mit folgenden Startcomment:

```
    /*
Plugin Name:    RRZE Hello Lenny
Plugin URI:     https://github.com/RRZE-Webteam/rrze-hello-lenny
Description:   Plugin Template for hybrid plugins. Inspired by Hello Dolly 
Version:        1.0.0
Author:         RRZE-Webteam
Author URI:     https://wordpress.rrze.fau.de/
License:        GNU General Public License Version 3
License URI:    https://www.gnu.org/licenses/gpl-3.0.html
Domain Path:    /languages
Text Domain:    rrze-hello-lenny
*/
```

- Mimimale Dateistruktur im Hauptverzeichnis

```
LICENSE
README.md
rrze-hello-lenny.php
package.json
src/js/
src/sass/
assets/js/
assets/css/
includes/
includes/Main.php
includes/Shortcodes.php
includes/Block-Editor.php
languages/
languages/rrze-hello-lenny-de_DE.mo
languages/rrze-hello-lenny-de_DE.po

```

**Comment by rvdforst** [comment]
In Plugins, in denen Webpack verwendet wird, um die Distributionsdateien zu erstellen, wird empfohlen, das Verzeichnis src/ für die Quelldateien (js, tsx, scss etc.), die bearbeitet werden können, zu verwenden und das Verzeichnis build/ für die finalen Distributionsdateien, die nicht bearbeitet werden. Für größere Projekte (wie rrze-newsletter) ist es ratsam, Unterverzeichnisse unter src/ zu verwenden. Dieses Schema ist das am häufigsten verwendete. Das Verzeichnis assets wird für diesen Aufbau nicht mehr verwendet.
