### ISSUE TITLE
Spracherkennung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-hello-lenny#9]
Das Plugin soll die Sprache der Website erkennen un diese Sprache bei der #4 im lang-Attribut und in der Auswahl der Ausgabe anzugeben

**Comment by thenickless** [comment]
done 

https://github.com/RRZE-Webteam/rrze-hello-lenny/commit/ad9b073c87aa54ef5235ff35328f5cb7195b2fa7
